### ISSUE TITLE
xquic在minitopo中的实验请教

### ISSUE THREAD

**Issue by Flysniper99** [NetExperimentEasy/mpquic-exp#1]
我在复现本实验的时候一直跑不出来pacp文件，找了蛮久的原因没找到，所以在这里向您请教一下。
我的mptcp安装没有问题，在mptcp的测试网站上试过；xquic的多路径实验我也能跑通（在两台buntu物理机上进行的实验，使用以太网以及wifi路径）。但是使用您的exp和topo文件在mininet跑xquic一直不成功。
下图是cmd的一些info。能烦请您帮我看看问题出在哪里吗？
![7 8](https://github.com/NetExperimentEasy/mpquic-exp/assets/60088704/da8b9692-b3c3-4c7d-b1f6-b1f11d1a9ac6)

**Comment by derekwin** [comment]
我看了下日志，没发现异常。
我感觉需要排查一下客户端和服务端是否正常：
1. 首先是检查下配置指向的xquic编译目录是否正常
2. 其次是密钥文件是否生成了
3. 是xquic的客户端和服务端程序有没有调整MAX_BUF_SIZE，（默认值太小，这个需要调大），参考这个仓库的改法https://github.com/NetExperimentEasy/static-build-xquic/blob/main/src/test_client.c
![image](https://github.com/NetExperimentEasy/mpquic-exp/assets/23076088/1b55ff91-1117-457a-9dfb-e594c0792bdd)
4. 可以手动mininet启一个简单的拓扑，在两端跑下服务端和客户端，看能不能启动。

**Comment by derekwin** [comment]
通过微信沟通，已经解决问题，故关闭此issue。
