### ISSUE TITLE
testclient

### ISSUE THREAD

**Issue by whyere** [NetExperimentEasy/mpquic-exp#2]
大佬可以分享一下，两个shared library 的源文件吗?

**Comment by derekwin** [comment]
不好意思，现在才看到。
因为时间很长了，当时的文件已经没有了。
我记得当时编译的应该是xquic 1.4，所以你可以试试用xquic官方仓库1.4来编译动态库.
另外，本仓库里面的客户端我没记错的话，应该是静态编译之后的，大概率是可以直接运行的。

**Comment by derekwin** [comment]
这个是使用xmake静态编译客户端的仓库：https://github.com/NetExperimentEasy/static-build-xquic
